meta:
  type: editor-config
  version: 0.7

minScale: 0.1
maxScale: 5
senseRange: 15

semantics:
  tags:
    - name: room
      styles:
        fill: '#cccccc'
        stroke: '#999999'
        strokeWidth: 2
    - name: staircase
      styles:
        fill: '#d4eb8b'
        stroke: '#999999'
        strokeWidth: 2
    - name: hallway
      styles:
        fill: '#ffffff'
        stroke: 'none'
    - name: door
      styles:
        stroke: '#666666'
        strokeWidth: 4
