meta:
  type: editor-config
  version: 0.7

minScale: 0.5
maxScale: 5
senseRange: 15

semantics:
  tags:
    - name: room
      styles:
        fill: '#f4f4f4'
        stroke: '#cccccc'
    - name: staircase
      styles:
        fill: '#d4eb8b'
        stroke: '#cccccc'
    - name: hallway
      styles:
        fill: '#ffffff'
        stroke: 'none'
    - name: door
      styles:
        stroke: '#a2a1a1'
